# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Build & Lint (Bun FTW! )

on:
  workflow_dispatch:

  pull_request:

  push:
    branches:
      - next
      - main

env:
  NODE_VERSION: lts/*

jobs:
  build-lint-ts:
    name: Build & Lint Typescript (Bun Style )
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: ⤵️ Checkout repository
        uses: actions/checkout@v4.1.2

      - name: Install Bun
        uses: oven-sh/setup-bun@v1 # Install Bun for our workflow

      - name: Install dependencies
        run: bun install # Use Bun's package manager

      - name: Build Typescript
        run: bun build # Leverage Bun's built-in build functionality

      - name: Run ESLint
        run: bun run lint # Execute ESLint using Bun's task runner (if applicable)
