# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Publish with Bun

on:
  workflow_dispatch:

  release:
    types:
      - created

env:
  NODE_VERSION: lts/*

jobs:
  publish-with-bun:
    name: Publish with Bun
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: ⤵️ Checkout repository
        uses: actions/checkout@v4.1.2

      - name: Setup Node.js (for Bun)
        uses: actions/setup-node@v4.0.2
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install Bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies (Bun)
        run: bun install --frozen

      - name: Build Typescript
        run: bun build

      - name: Publish (with Bun)
        run: bun run publish --yes
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
